# Définit le nom de l'application, utile pour l'identifier dans les logs ou les outils de monitoring
spring.application.name=senegal-trip-planner

# Spécifie le port sur lequel le serveur web embarqué (Tomcat) va écouter
# Le port 8080 est le port par défaut pour le développement web local
server.port=8080

# Configure le niveau de log pour le package de notre application
# Le niveau 'DEBUG' permet de voir les détails techniques en console, utile pour vérifier nos calculs de graphes
logging.level.sn.tripplanner=DEBUG

# Désactive l'affichage de la bannière Spring Boot au démarrage pour garder une console de sortie plus propre
spring.main.banner-mode=off

# Configuration pour permettre l'envoi de données complexes via les contrôleurs REST
# Assure que les réponses JSON sont bien formatées (indentées) pour faciliter la lecture durant le développement
spring.jackson.serialization.indent-output=true